name: Secrets
on: push
jobs:
  job_one:
    runs-on: ubuntu-latest
    # if the secret in in an environment it has to be specified 
    # for this to work there must be a environment named "test_environment"
    environment: test_environment
    # for this to work there must be a secret named MY_SECRET_ONE
    env:
      MY_SECRET: ${{ secrets.MY_SECRET_ONE }}
    steps:
      - name: First step
        run: echo "'Secret via env:' ${{ env.MY_SECRET }}"
      - name: Second step
        run: echo "'Secret via secrets:'' ${{ secrets.MY_SECRET_ONE }}"