name: Variables
on: push
env:
  WORKFLOW_LEVEL_VARIABLE: Hello
jobs:
  job_one:
    runs-on: ubuntu-latest
    env:
      JOB_LEVEL_VARIABLE: World
    steps:
      - name: First step
        env:
          STEP_LEVEL_VARIABLE: It's about variables
        run: echo "${{ env.WORKFLOW_LEVEL_VARIABLE }} ${{ env.JOB_LEVEL_VARIABLE}}. ${{ env.STEP_LEVEL_VARIABLE }}"
      # The following will only work if there is a repository variable with the name REPOSITORY_VARIABLE
      #- name: Second step
      #  run: echo "${{ vars.REPOSITORY_VARIABLE }}"