name: Conditions
on:
  - push
  - workflow-dispatch
jobs:
  job_one:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Critical step
        id: critical_step_id
        # for step failing change to: run: exit 1
        run: exit 0
      - name: On failure step
        if: ${{ failure() && steps.critical_step_id.conclusion == 'failure' }}
        run: echo "ERROR"
      - name: On success step
        if: ${{ success() && steps.critical_step_id.conclusion == 'success' }}
        run: echo "SUCCESS"
      - name: Always
        if: ${{ always() }}
        run: echo "ALWAYS"
  job_two:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name:
        run: echo "this job is only executed when pushing"