name: Conditions
on: push
jobs:
  job_one:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Critical step
        id: critical_step_id
        run: exit 0
      - name: On failure step
        if: ${{ failure() && steps.critical_step_id.conclusion == 'failure' }}
        run: echo "ERROR"
      - name: On success step
        if: ${{ success() && steps.critical_step_id.conclusion == 'success' }}
        run: echo "SUCCESS"
      - name: Always
        if: ${{ always() }}
        run: echo "ALWAYS"