name: Conditions
on: push
jobs:
  job_one:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Failing step
        id: failing_step_id
        run: exit 1
      - name: On failure step
        if: ${{ failure() && steps.failing_step_id.conclusion == 'failure' }}
        run: echo "ERROR"
      - name: On success step
        if: ${{ failure() && steps.failing_step_id.conclusion == 'failure' }}
        run: echo "SUCCESS"
  job_failure:
    if: ${{ failure() }} 
    runs-on: ubuntu-latest
    steps:
      - name: Failure
        run: echo "A previous job has faild"
  job_sucess:
    if: ${{ success() }} 
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo "All previous jobs have suceeded"
  job_always:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Always
        run: echo "This is always printed"