name: Outputs
on: push
jobs:
  create_output:
    runs-on: ubuntu-latest
    outputs:
      output_one: ${{ steps.create_output_one.outputs.step_output_one }}
      output_two: ${{ steps.create_output_two.outputs.step_output_two}}
    steps:
      - name: Create output one
        id: create_output_one
        run: echo "step_output_one=Hello world" >> $GITHUB_OUTPUT
      - name: Create output two
        id: create_output_two
        run: echo "step_output_two=This is some output" >> $GITHUB_OUTPUT
  use_output:
    needs: create_output
    runs-on: ubuntu-latest
    steps:
      - name: Use and print output one
        run: echo "${{ needs.create_output.outputs.output_one }}"
      - name: Use and print output two
        run: echo "${{ needs.create_output.outputs.output_two }}"